### ISSUE TITLE
Client.get_data_row_by_global_key throws wrong exception on not found

### ISSUE THREAD

**Issue by adam-homeboost** [Labelbox/labelbox-python#1260]
Client.get_data_row_by_global_key throws `MalformedQueryException` instead of `ResourceNotFoundError` which is very misleading.

Also, the presence of data in "fetchedDataRows" is also very misleading.  I would expect this to be empty instead of a value with blank id in it.

```
[2023-10-12 22:38:56,741: DEBUG/MainProcess] https://api.labelbox.com:443 "POST /graphql HTTP/1.1" 200 None
[2023-10-12 22:38:56,742: DEBUG/MainProcess] Response: {"data":{"dataRowsForGlobalKeysResult":{"data":{"fetchedDataRows":[{"id":""}],"notFoundGlobalKeys":["rev_3PjYIxtGMwZofBnToC2Pjz"],"accessDeniedGlobalKeys":[]},"jobStatus":"COMPLETE"}}}

[2023-10-12 22:38:56,744: WARNING/MainProcess] There are errors present. Please look at 'errors' in the returned dict for more details
[2023-10-12 22:38:56,750: ERROR/MainProcess] Task upload_recipe_event_image_to_labelbox[cd8a46ed-9c40-46fc-80a7-277b2f07ae2b] raised unexpected: MalformedQueryException({'global_key': 'rev_3PjYIxtGMwZofBnToC2Pjz', 'error': 'Data Row not found'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/hearth-tasks/hearth_tasks/tasks_labelbox.py", line 86, in upload_recipe_event_image_to_labelbox
    data_row = lb_client.get_data_row_by_global_key(recipe_event["recipe_event_id"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/labelbox/client.py", line 739, in get_data_row_by_global_key
    raise labelbox.exceptions.MalformedQueryException(res['errors'][0])
labelbox.exceptions.MalformedQueryException: {'global_key': 'rev_3PjYIxtGMwZofBnToC2Pjz', 'error': 'Data Row not found'}
```

**Comment by jannyzhao** [comment]
Hi there,

Please ensure you're retrieving the correct `global_key` from your data row. If the `global_key `does not exist, you can use `client.get_data_row("<data_row_id>")` and retrieve the `data_row_id`. 

Here's more information: https://docs.labelbox.com/reference/data-row#get-a-data-row

**Comment by Gabefire** [comment]
Hey,
I see what you are saying Ill look at getting that changed since global_keys can have almost any format it should just be ResourceNotFoundError. 
Thanks,
Gabe
