### ISSUE TITLE
Labelbox 3.11.1 Dependency Problem

### ISSUE THREAD

**Issue by arhanjain** [Labelbox/labelbox-python#394]
Hey,

I'm having trouble running my Python code with the latest Labelbox release (3.11.1). I've been using the previous version (3.11.0) and it's been working without any issues for my purposes (AI as a part of a high school club). Here is the issue that arises.

![image](https://user-images.githubusercontent.com/43100506/149462497-b2c85b8e-d093-460d-aba5-d1a4bfa74cd0.png)

I can confirm that running the exact same code with Labelbox 3.11.0 doesn't yield this issue.

![image](https://user-images.githubusercontent.com/43100506/149462631-abd365cc-97aa-4774-a593-f0e5bc1f9152.png)

P.S. Apologies if my issue description isn't the best - I'm pretty new to creating issues in GitHub and am still learning. Let me know if any further information is required.

**Comment by arhanjain** [comment]
I am running Python 3.8.12. Running the import, `from labelbox.data.serialization import LBV1Converter`, yields the following on labelbox 3.11.1.

Result:
`>>> from labelbox.data.serialization import LBV1Converter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/serialization/__init__.py", line 1, in <module>
    from .labelbox_v1 import LBV1Converter
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/serialization/labelbox_v1/__init__.py", line 1, in <module>
    from .converter import LBV1Converter
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/serialization/labelbox_v1/converter.py", line 1, in <module>
    from labelbox.data.serialization.labelbox_v1.objects import LBV1Mask
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/serialization/labelbox_v1/objects.py", line 5, in <module>
    from .classification import LBV1Checklist, LBV1Classifications, LBV1Radio, LBV1Text, LBV1Dropdown
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/serialization/labelbox_v1/classification.py", line 5, in <module>
    from .feature import LBV1Feature
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/serialization/labelbox_v1/feature.py", line 6, in <module>
    from ...annotation_types.types import Cuid
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/annotation_types/__init__.py", line 1, in <module>
    from .geometry import Line
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/annotation_types/geometry/__init__.py", line 3, in <module>
    from .mask import Mask
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/annotation_types/geometry/mask.py", line 9, in <module>
    from ..data import MaskData
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/annotation_types/data/__init__.py", line 1, in <module>
    from .raster import ImageData
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/annotation_types/data/raster.py", line 13, in <module>
    from ..types import TypedArray
  File "/home/owhan/miniconda3/envs/labelbox-testing/lib/python3.8/site-packages/labelbox/data/annotation_types/types.py", line 5, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging`

**Comment by msokoloff1** [comment]
Fixed in 3.12.0. Thanks for bringing this to my attention.
