### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by caleb-artifact** [Labelbox/labelbox-python#48]
I'm getting these errors pretty consistently with the labelbox API.  It would be nice if the client was more self healing, but at a bare minimum it would be nice to have a better error thrown than JSONDecodeError.  Some sort of HTTP error that lets me know what status code was returned so the application can handle retries appropriately. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/labelbox/client.py", line 124, in execute
    response = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 267, in <module>
    lbImporter.sync()
  File "./main.py", line 137, in sync
    for row in dataset_rows:
  File "/usr/local/lib/python3.8/site-packages/labelbox/pagination.py", line 50, in __next__
    results = self.client.execute(query, self.params)
  File "/usr/local/lib/python3.8/site-packages/labelbox/client.py", line 126, in execute
    raise labelbox.exceptions.LabelboxError(
labelbox.exceptions.LabelboxError: Failed to parse response as JSON: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.17.7</center>
</body>
</html>
('Failed to parse response as JSON: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.17.7</center>\r\n</body>\r\n</html>\r\n', None)
```

**Comment by rllin** [comment]
thanks for the feedback.  this is definitely on the roadmap.  we also very much welcome any contributions!

were you able to accomplish (eventually) what you wished to?

**Comment by caleb-artifact** [comment]
Currently we are running this script locally and fortunately we have made it self-healing when it is re-run.  We can check to see if the `labelbox.exceptions.LabelboxError.message` contains `502 Bad Gateway` but this seems a little hacky.

**Comment by rllin** [comment]
handled by

https://github.com/Labelbox/labelbox-python/pull/55/files#diff-7d438bd9407a39c1368b718c547d2541R64-R131

in https://github.com/Labelbox/labelbox-python/releases/tag/v2.4.5 :)

please lmk if you see anything else similar
