### ISSUE TITLE
UnboundLocalError: local variable 'coco_segment_info' referenced before assignment

### ISSUE THREAD

**Issue by OttomanZ** [Labelbox/labelbox-python#788]
Hi, @Labelbox I am exporting my labelbox project using the Python SDK to COCO Format following the official docs, but during the conversion process using panoptic serialization, it encounters the following error.

I am attaching the Source code and full traceback below.
```python
import os
import sys
import glob
import numpy as np
import argparse
from labelbox.data.annotation_types import Label, LabelList, ImageData, Point, ObjectAnnotation, Rectangle, Polygon
from labelbox.data.serialization import COCOConverter
import json
from datetime import datetime
import labelbox as lb
import labelbox2coco as lb2co




class Converter:
    def __init__(self, api_key, project_id, dataset_id, endpoint):
        self.lb_api_key = api_key
        self.project_id = project_id
        self.dataset_id = dataset_id
        self.endpoint = endpoint

        # now using the labelbox api to get the export.json file
        client = lb.Client(self.lb_api_key, self.endpoint)
        ## Get labelbox project
        project = client.get_project(self.project_id)
        print(f'[{datetime.now()}] SUCCESSFULLY CONNECTED TO LABELBOX SERVERS USING SDK.')

        labels = project.label_generator()
        coco_dict = COCOConverter.serialize_panoptic(
            labels,
            './images',
            './masks',
            all_stuff=True,
            ignore_existing_data=True
        )
        
        # write dict to json file
        
        labels = project.export_labels(download = True, start="1970-01-01", end="2022-12-04")
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--task_json', type=str, default = './task.json', help='Path to task.json for MAL.')
    args = parser.parse_args()
    with open(args.task_json, 'r') as f:
        task = json.load(f)
    # Loading the task parameters into memory
    project_id = task['PROJECT_ID']
    dataset_id = task['DATASETS']
    api_key = task['LB_API_KEY']
    print('[+] Project ID: {}'.format(project_id))
    print('[+] Dataset ID: {}'.format(dataset_id))

    print(f'[{datetime.now()}] STARTED LABELBOX MAL SETUP. CONVERTING LABELBOX JSON TO COCO FORMAT.')    

    converter_obj = Converter(api_key=api_key, project_id=project_id, dataset_id=dataset_id, endpoint='https://api.labelbox.com/graphql')

```
## Full Traceback

```bash
[2022-12-04 14:09:14.208175] STARTED LABELBOX MAL SETUP. CONVERTING LABELBOX JSON TO COCO FORMAT.
[2022-12-04 14:09:16.233525] SUCCESSFULLY CONNECTED TO LABELBOX SERVERS USING SDK.
0it [00:00, ?it/s]concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/muneeb/.local/lib/python3.10/site-packages/labelbox/data/serialization/coco/panoptic_dataset.py", line 101, in process_label
    if coco_segment_info is None:
UnboundLocalError: local variable 'coco_segment_info' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/muneeb/detectron2-workflow/labelbox_coco_converter.py", line 67, in <module>
    converter_obj = Converter(api_key=api_key, project_id=project_id, dataset_id=dataset_id, endpoint='https://api.labelbox.com/graphql')
  File "/home/muneeb/detectron2-workflow/labelbox_coco_converter.py", line 37, in __init__
    coco_dict = COCOConverter.serialize_panoptic(
  File "/home/muneeb/.local/lib/python3.10/site-packages/labelbox/data/serialization/coco/converter.py", line 90, in serialize_panoptic
    return CocoPanopticDataset.from_common(labels=labels,
  File "/home/muneeb/.local/lib/python3.10/site-packages/labelbox/data/serialization/coco/panoptic_dataset.py", line 142, in from_common
    results = [
  File "/home/muneeb/.local/lib/python3.10/site-packages/labelbox/data/serialization/coco/panoptic_dataset.py", line 143, in <listcomp>
    future.result() for future in tqdm(as_completed(futures))
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
UnboundLocalError: local variable 'coco_segment_info' referenced before assignment
```

**Starting Lines from my JSON File**

```json
{"ID":"REDACTED","DataRow ID":"REDACTED","Labeled Data":"https://storage.labelbox.com/redacted","Label":{"objects":[{"featureId":"redacted","schemaId":"redacted","color":"#1CE6FF","title":"contract_number","value":"contract_number","bbox":{"top":225,"left":440,"height":54,"width":171},"instanceURI":"https://api.labelbox.com/masks/feature/redacted"},{"featureId":"redacted","schemaId":"redacted","color":"#FF34FF","title":"date","value":"date","bbox":{"top":316,"left":1051,"height":40,"width":228},"instanceURI":"https://api.labelbox.com/masks/feature/redacted"},{"featureId":"clb24mnr10007356kgmtx30ae","schemaId":"clb24l82821ow07z55k1ga35z","color":"#FF4A46","title":"ship_to","value":"ship_to","bbox":{"top":399,"left":1056,"height":40,"width":217},"instanceURI":"https://api.labelbox.com/masks/feature/"}],"classifications":[],"relationships":[]},"Created By":"muneeb@muneeb.co","Project Name":"REDACTED","Created At":"2022-11-29T11:18:44.000Z","Updated At":"2022-11-29T11:18:47.000Z","Seconds to Label":63.436,"Seconds to Review":0,"Seconds to Create":63.436,"External ID":"0ae5e7af-921d-4201-9f08-63525d1bee5f.jpg","Global Key":null,"Agreement":-1,"Is Benchmark":0,"Benchmark Agreement":-1,"Benchmark ID":null,"Dataset Name":"Redacted","Reviews":[],"View Label":"https://editor.labelbox.com?project=redacted","Has Open Issues":0,"Skipped":false,"DataRow Workflow Info":{"taskId":"6a701aa5-9118-45e8-a6fe-e30416b1f9a4","taskName":"Initial review task","Workflow History":[{"actorId":"cl9qausb937a307z0fpm62hdm","action":"MOVE","createdAt":"2022-11-29T11:18:47.321Z","previousTaskId":"e043ab38-dd55-0ac5-a8c1-d995e0944c44","previousTaskName":"Initial labeling task","nextTaskId":"6a701aa5-9118-45e8-a6fe-e30416b1f9a4","nextTaskName":"Initial review task"},{"actorId":"cl9qausb937a307z0fpm62hdm","action":"MOVE","createdAt":"2022-11-29T11:18:46.352Z","nextTaskId":"e043ab38-dd55-0ac5-a8c1-d995e0944c44","nextTaskName":"Initial labeling task"}]}},

{"ID":"REDACTED","DataRow ID":"REDACTED","Labeled Data":"REDACTED","Label":{"objects":[{"featureId":"REDACTED","schemaId":"REDACTED","color":"#1CE6FF","title":"contract_number","value":"contract_number","bbox":{"top":250,"left":422,"height":55,"width":172},"instanceURI":"redacted"},{"featureId":"clb24n4j9000d356kt9pj2r0x","schemaId":"clb24l82721ov07z5a7td1g4g","color":"#FF34FF","title":"date","value":"date","bbox":{"top":341,"left":1024,"height":37,"width":242},"instanceURI":""},{"featureId":"clb24n92d000g356kuga5o5wt","schemaId":"clb24l82821ow07z55k1ga35z","color":"#FF4A46","title":"ship_to","value":"ship_to","bbox":{"top":420,"left":1029,"height":39,"width":192},"instanceURI":""},{"featureId":"clb24nex2000i356k82unmn0l","schemaId":"clb24hdld2cqm07zbf3ifdtat","color":"#008941","title":"itemcode","value":"itemcode","polygon":[{"x":26.022,"y":691.928},{"x":28.689,"y":897.261},{"x":139.355,"y":893.261},{"x":140.689,"y":690.595}],"instanceURI":""},{"featureId":"clb24nnr9000j356kqxfddj1u","schemaId":"clb24hdld2cqo07zb68st1p3m","color":"#006FA6","title":"barcode","value":"barcode","polygon":[{"x":287.355,"y":887.928},{"x":139.355,"y":889.261},{"x":138.022,"y":690.595},{"x":286.022,"y":690.595}],"instanceURI":""},{"featureId":"clb24nw3p000k356kpfr1ckw8","schemaId":"clb24hdld2cqq07zbc10vg8nk","color":"#A30059","title":"desc","value":"desc","polygon":[{"x":286.022,"y":914.595},{"x":768.689,"y":913.261},{"x":767.355,"y":685.261},{"x":283.355,"y":687.928}],"instanceURI":""},{"featureId":"clb24oenx000l356kql2io3y9","schemaId":"clb24hdld2cqs07zbh02a1b0v","color":"#FFDBE5","title":"packing","value":"packing","polygon":[{"x":765.355,"y":682.595},{"x":770.689,"y":914.595},{"x":1009.355,"y":914.595},{"x":1009.355,"y":682.595}],"instanceURI":""},{"featureId":"clb24omeu000m356krkm1adbh","schemaId":"clb24hdld2cqu07zbf4wq9qy9","color":"#7A4900","title":"qtyunit","value":"qtyunit","polygon":[{"x":1006.689,"y":683.928},{"x":1260.022,"y":681.261},{"x":1260.022,"y":898.595},{"x":1013.355,"y":903.928}],"instanceURI":""}],"classifications":[],"relationships":[]},"Created By":"muneeb@muneeb.co","Project Name":"REDACTED","Created At":"2022-11-29T11:20:21.000Z","Updated At":"2022-11-29T11:20:22.000Z","Seconds to Label":98.241,"Seconds to Review":0,"Seconds to Create":98.241,"External ID":"0af26c86-75e4-45ce-bcfc-ffa99fc0c3ef.jpg","Global Key":null,"Agreement":-1,"Is Benchmark":0,"Benchmark Agreement":-1,"Benchmark ID":null,"Dataset Name":"REDACTED","Reviews":[],"View Label":"","Has Open Issues":0,"Skipped":false,"DataRow Workflow Info":{"taskId":"6a701aa5-9118-45e8-a6fe-e30416b1f9a4","taskName":"Initial review task","Workflow History":[{"actorId":"cl9qausb937a307z0fpm62hdm","action":"MOVE","createdAt":"2022-11-29T11:20:21.797Z","previousTaskId":"e043ab38-dd55-0ac5-a8c1-d995e0944c44","previousTaskName":"Initial labeling task","nextTaskId":"6a701aa5-9118-45e8-a6fe-e30416b1f9a4","nextTaskName":"Initial review task"},{"actorId":"cl9qausb937a307z0fpm62hdm","action":"MOVE","createdAt":"2022-11-29T11:20:21.772Z","nextTaskId":"e043ab38-dd55-0ac5-a8c1-d995e0944c44","nextTaskName":"Initial labeling task"}]}},

```

## My Data Labeling Format

![image](https://user-images.githubusercontent.com/79105382/205483282-325d4690-c86f-41b0-8579-9b00cb12348e.png)

**Comment by OttomanZ** [comment]
@farkob Am I missing something here.

**Comment by OttomanZ** [comment]
Hi, So I ended up missing the following function, `serialize_instances` which seems to do the trick as follows,
![image](https://user-images.githubusercontent.com/79105382/205512941-c88d3b5c-c975-4e34-b6b9-f90ba59204ce.png)

For training on detectron2 I used the following code,

```python
import os
import sys
import warnings
import logging
import logging.handlers
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import argparse
import hashlib
import detectron2
from detectron2.data.datasets import register_coco_instances
from detectron2.data import transforms as T
import json
import random
from detectron2.structures import BoxMode
from detectron2.data import DatasetCatalog, MetadataCatalog
import cv2
from detectron2.utils.visualizer import Visualizer
import uuid
from detectron2.engine import DefaultTrainer, DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import ColorMode
from detectron2 import model_zoo 

# registering the exported coco format dataset to detectron2
# ref: https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#register-a-coco-format-dataset
register_coco_instances("my_dataset", {}, "coco.json", "./images/")
fruits_nuts_metadata = MetadataCatalog.get("my_dataset")
dataset_dicts = DatasetCatalog.get("my_dataset")
for d in random.sample(dataset_dicts, 3):
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, ::-1], metadata=fruits_nuts_metadata, scale=0.5)
    vis = visualizer.draw_dataset_dict(d)
    cv2.imshow(str(uuid.uuid4()),vis.get_image()[:, :, ::-1])
    cv2.waitKey(0)

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("my_dataset",)
cfg.DATASETS.TEST = ()  # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml")  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02
cfg.SOLVER.MAX_ITER = (
    300
)  # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (
    128
)  # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3  # 3 classes (data, fig, hazelnut)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5   # set the testing threshold for this model
cfg.DATASETS.TEST = ("my_dataset", )
predictor = DefaultPredictor(cfg)

for d in random.sample(dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=fruits_nuts_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    cv2.imshow(str(uuid.uuid4()),v.get_image()[:, :, ::-1])
    cv2.waitKey(0)

cv2.destroyAllWindows()



```
