### ISSUE TITLE
importing error

### ISSUE THREAD

**Issue by marcoramosw** [Labelbox/labelbox-python#86]
I am not able to import labelbox, the following error occurs:
Traceback (most recent call last):
  File "Y:/Segmentation/labelbox.py", line 2, in <module>
    from labelbox import Client
  File "Y:\Segmentation\labelbox.py", line 2, in <module>
    from labelbox import Client
ImportError: cannot import name 'Client' from partially initialized module 'labelbox' (most likely due to a circular import)

**Comment by marcoramosw** [comment]
solved it, nevermind
